[project]
authors = [
    {name = "codetricksters", email = "leonardo.magic@hotmail.com"},
]
requires-python = "<4.0,>=3.11"
dependencies = [
    "requests>=2.31.0,<3.0.0",
    "typer>=0.15.2,<1.0.0",
    "pydantic-settings>=2.0",
]
name = "uau-api"
version = "1.0.0"
description = ""
readme = "README.md"

[dependency-groups]
dev = [
    "cython>=3.0",
    "mypy>=1.20.1",
    "setuptools>=82.0.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["uau_api*"]
