__test__: dict

class BaseAPI:
    def __init__(self, *args, **kwargs) -> None: ...
    def delete(self, *args, **kwargs): ...
    def get(self, *args, **kwargs): ...
    def post(self, *args, **kwargs): ...
    def put(self, *args, **kwargs): ...
