import uau_api.requestsapi
from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class UauAPI(uau_api.requestsapi.RequestsApi):
    def __init__(self, *args, **kwargs) -> None: ...
    def authenticate(self, *args, **kwargs): ...
    def get_session(self, *args, **kwargs): ...
