import aiohttp
from _typeshed import Incomplete
from datetime import datetime
from pathlib import Path
from pydantic import BaseModel
from uau_api.requestsapi import RequestsApi as RequestsApi
from uau_api.settings import Settings as Settings

logger: Incomplete
file_handler: Incomplete
log_format: Incomplete

class Processo(BaseModel):
    NumeroProcesso: int
    Empresa: int
    Obra: str

class EmpresaObra(BaseModel):
    Empresa: int
    Obra: str

class EmpresaObraPeriodo(BaseModel):
    EmpresaObra: list[EmpresaObra]
    PeriodoInicial: str
    PeriodoFinal: str

class Fornecedor(BaseModel):
    cnpjFornecedor: str

class DadosFornecedor(BaseModel):
    Fornecedor: list[Fornecedor]
    PeriodoInicial: str
    PeriodoFinal: str

class RootModel(BaseModel):
    Processos: list[Processo] | None
    EmpresaObraPeriodo: EmpresaObraPeriodo
    FornecedorPeriodo: DadosFornecedor | None

def exception_handler(func): ...

class Uau(RequestsApi):
    headers: Incomplete
    def __init__(self, url) -> None: ...
    @property
    def is_authenticated(self): ...
    def login(self, login: str, senha: str): ...
    def get_session(self): ...
    def get_headers(self): ...
    @staticmethod
    def query_construct(empresa_obra: list[dict], periodo_inicial: datetime, periodo_final: datetime, processos: list[int] | None = None, fornecedores: list[dict] | None = None) -> RootModel: ...
    @exception_handler
    def get_users(self, username=None): ...
    @exception_handler
    def inserir_insumo(self, insumo): ...
    @exception_handler
    def gerar_itens_processo(self, item: str, quantidade: float, preco: float, cap: str, categoria_movimentacao_financeira: str, unidade: str, vinculo_pl_item: str, vinculo_pl_codigo_produto: int, vinculo_pl_contrato: int, vinculo_pl_servico: str, vinculo_pl_insumo: str, vinculo_pl_mes_planejamento: str, vinculo_pl_quantidade: float, vinculo_pl_preco: float): ...
    @exception_handler
    def gerar_processo_pagamento(self, empresa: int, obra: str, codigo_fornecedor: int, nome_fornecedor: str, tipo_processo: int, controlar_estoque: int, acompanha_entrega: int, tipo_item: int, parametro_codigo_departamento: str, parametro_taxa_juros: int, parametro_taxa_multa: int, parametro_tipo_juros: int, parametro_retroagir: int, parcelas_datavencimento: str, parcelas_valor: float, parcelas_banco: str, parcelas_conta: str, parcelas_tipo_emissao: str, parcelas_forma_pagamento: str, parcelas_tipo_pagamento: str, parcelas_codigo_de_barras: str, parcelas_observacao_pagamento: str, parcelas_data_documento_fiscal: str, parcelas_numero_documentofiscal: str, itens: list[dict]): ...
    @exception_handler
    def consultar_desembolso_planejamento(self, empresa: int, obra: str, mes_inicial: str, mes_final: str): ...
    @exception_handler
    def atualizar_servico_planejamento(self, data: dict) -> dict: ...
    @exception_handler
    def inserir_servico_planejamento_mes(self, data: dict): ...
    @exception_handler
    def atualizar_servico_planejamento_mes(self, data: dict): ...
    @exception_handler
    def atualizar_insumos_planejamento(self, data: dict): ...
    @exception_handler
    def exportar_planejamento_produto(self, empresa: int, obra: str) -> dict: ...
    @exception_handler
    def consultar_insumosGeral(self, insumo: str) -> dict: ...
    @exception_handler
    def consultar_pessoa_por_chave(self, codigo_pessoa: str) -> dict: ...
    @exception_handler
    def consultar_pessoas_por_cpf_cnpj(self, cpf_cnpj: str, status: str) -> dict: ...
    @exception_handler
    def consultar_contas_bancarias(self, codigo: int) -> dict: ...
    @exception_handler
    def obter_obras_ativas(self) -> dict: ...

class ProcessoPagamento(Uau):
    @exception_handler
    def consultar_processos(self, empresa_obra: list[dict], periodo_inicial: datetime, periodo_final: datetime, processos: list[dict] | None = None, fornecedores: list[dict] | None = None): ...
    @exception_handler
    def manutencao_processo(self, data: dict): ...
    def gerar_nota_fiscal(self, data: dict): ...
    @exception_handler
    def gerar_processo(self, data: dict): ...

async def async_download_file(session: aiohttp.ClientSession, url: str) -> bytes: ...
async def async_save_file(content: bytes, destination: Path) -> None: ...
async def process_item(session: aiohttp.ClientSession, url: str, destination: Path | str) -> None: ...
async def main(iterable, url, wd, destination): ...
