__test__: dict

class RequestsApi:
    def __init__(self, *args, **kwargs) -> None: ...
    def delete(self, *args, **kwargs): ...
    def get(self, *args, **kwargs): ...
    def get_headers(self, *args, **kwargs): ...
    def get_session(self, *args, **kwargs): ...
    def head(self, *args, **kwargs): ...
    def patch(self, *args, **kwargs): ...
    def post(self, *args, **kwargs): ...
    def put(self, *args, **kwargs): ...
    def request(self, *args, **kwargs): ...
