from _typeshed import Incomplete

class RequestsApi:
    base_url: Incomplete
    api_key: Incomplete
    session: Incomplete
    def __init__(self, base_url, api_key: str, session=None, **kwargs) -> None: ...
    def get_session(self): ...
    def get_headers(self): ...
    def request(self, method, url, **kwargs): ...
    def head(self, url, **kwargs): ...
    def get(self, url, **kwargs): ...
    def post(self, url, **kwargs): ...
    def put(self, url, **kwargs): ...
    def patch(self, url, **kwargs): ...
    def delete(self, url, **kwargs): ...
