import _abc
import inspect
import pydantic._internal._decorators
import pydantic.main
import pydantic_core._pydantic_core
from typing import ClassVar

__test__: dict

class ProcessSchema(pydantic.main.BaseModel):
    _abc_impl: ClassVar[_abc._abc_data] = ...
    model_config: ClassVar[dict] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    __class_vars__: ClassVar[set] = ...
    __private_attributes__: ClassVar[dict] = ...
    __pydantic_complete__: ClassVar[bool] = ...
    __pydantic_computed_fields__: ClassVar[dict] = ...
    __pydantic_core_schema__: ClassVar[dict] = ...
    __pydantic_custom_init__: ClassVar[bool] = ...
    __pydantic_decorators__: ClassVar[pydantic._internal._decorators.DecoratorInfos] = ...
    __pydantic_extra_info__: ClassVar[None] = ...
    __pydantic_fields__: ClassVar[dict] = ...
    __pydantic_generic_metadata__: ClassVar[dict] = ...
    __pydantic_parent_namespace__: ClassVar[dict] = ...
    __pydantic_post_init__: ClassVar[None] = ...
    __pydantic_serializer__: ClassVar[pydantic_core._pydantic_core.SchemaSerializer] = ...
    __pydantic_setattr_handlers__: ClassVar[dict] = ...
    __pydantic_validator__: ClassVar[pydantic_core._pydantic_core.SchemaValidator] = ...
    __signature__: ClassVar[inspect.Signature] = ...

class UserSchema(pydantic.main.BaseModel):
    _abc_impl: ClassVar[_abc._abc_data] = ...
    model_config: ClassVar[dict] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    __class_vars__: ClassVar[set] = ...
    __private_attributes__: ClassVar[dict] = ...
    __pydantic_complete__: ClassVar[bool] = ...
    __pydantic_computed_fields__: ClassVar[dict] = ...
    __pydantic_core_schema__: ClassVar[dict] = ...
    __pydantic_custom_init__: ClassVar[bool] = ...
    __pydantic_decorators__: ClassVar[pydantic._internal._decorators.DecoratorInfos] = ...
    __pydantic_extra_info__: ClassVar[None] = ...
    __pydantic_fields__: ClassVar[dict] = ...
    __pydantic_generic_metadata__: ClassVar[dict] = ...
    __pydantic_parent_namespace__: ClassVar[dict] = ...
    __pydantic_post_init__: ClassVar[None] = ...
    __pydantic_serializer__: ClassVar[pydantic_core._pydantic_core.SchemaSerializer] = ...
    __pydantic_setattr_handlers__: ClassVar[dict] = ...
    __pydantic_validator__: ClassVar[pydantic_core._pydantic_core.SchemaValidator] = ...
    __signature__: ClassVar[inspect.Signature] = ...
