import aiohttp
from pathlib import Path

def write_jsonl(data: dict | list[dict], filepath: str, mode: str = 'w'): ...
def save_base64_to_file(base64_string, output_filename) -> None: ...
def exception_handler(func): ...
async def async_download_file(session: aiohttp.ClientSession, url: str) -> bytes: ...
async def async_save_file(content: bytes, destination: Path) -> None: ...
async def process_url(session: aiohttp.ClientSession, url: str, destination: Path | str) -> None: ...
