from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class AcompanharEntrega:
    def __init__(self, *args, **kwargs) -> None: ...
    def acompanhar_pre_entrega(self, *args, **kwargs): ...
    def consultar_processos(self, *args, **kwargs): ...
