from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class AcompanhamentosServicos:
    def __init__(self, *args, **kwargs) -> None: ...
    def acompanhar_contrato(self, *args, **kwargs): ...
    def acompanhar_servico_contrato(self, *args, **kwargs): ...
    def acompanhar_servico_orcado(self, *args, **kwargs): ...
    def acompanhar_servico_pl(self, *args, **kwargs): ...
    def alterar_acompanhamento_servico_contrato(self, *args, **kwargs): ...
    def consultar_acompanhamento_contrato_servico_por_contrato_eservico(self, *args, **kwargs): ...
    def consultar_acompanhamento_contrato_servico_por_servico(self, *args, **kwargs): ...
    def excluir_acompanhamento_servico_de_contrato(self, *args, **kwargs): ...
    def excluir_acompanhamento_servico_orcado(self, *args, **kwargs): ...
    def excluir_acompanhamento_servico_orcado_por_chave(self, *args, **kwargs): ...
    def excluir_acompanhamento_servico_pl(self, *args, **kwargs): ...
