from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Anexo:
    def __init__(self, *args, **kwargs) -> None: ...
    def anexar_arquivo(self, *args, **kwargs): ...
    def anexar_arquivos_base64_request(self, *args, **kwargs): ...
    def anexar_base64_imagem(self, *args, **kwargs): ...
    def baixar_arquivos(self, *args, **kwargs): ...
    def consultar_chaves_comentario(self, *args, **kwargs): ...
    def excluir_anexos(self, *args, **kwargs): ...
    def gravar_comentario_anexo(self, *args, **kwargs): ...
    def lista_arquivo_por_chave(self, *args, **kwargs): ...
    def listar_armazenamentos(self, *args, **kwargs): ...
    def listar_diretorios(self, *args, **kwargs): ...
    def retorna_arquivo_em_bytes(self, *args, **kwargs): ...
    def retornar_arquivos_em_lista_bytes(self, *args, **kwargs): ...
