import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Anexo:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def anexar_arquivo(self, arquivo: str | None = None, nome: str | None = None, caminho: str | None = None, identificador: str | None = None, usuario: str | None = None, caminho_exclusivo: str | None = None, controla_anexouau_web: bool | None = None) -> requests.Response: ...
    def excluir_anexos(self, identificador: str | None = None, nome_arquivo: str | None = None, origem: int | None = None) -> requests.Response: ...
    def baixar_arquivos(self, arquivos: list[dict] = None) -> requests.Response: ...
    def listar_diretorios(self, caminho: str | None = None, origem: int | None = None) -> requests.Response: ...
    def anexar_base64_imagem(self, arquivo: str | None = None, nome: str | None = None, caminho: str | None = None, identificador: str | None = None, usuario: str | None = None, extensao_imagem: str | None = None, caminho_exclusivo: str | None = None, controla_anexouau_web: bool | None = None, origem: int | None = None) -> requests.Response: ...
    def lista_arquivo_por_chave(self, chave: str = None, valores: list[str] = None) -> requests.Response: ...
    def listar_armazenamentos(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def gravar_comentario_anexo(self, chave: str | None = None, campos: str | None = None, usuario: str | None = None, comentario: str | None = None, tipo_comentario: str | None = None, usuario_privado: list[dict] | None = None, grupo_privado: list[dict] | None = None) -> requests.Response: ...
    def retorna_arquivo_em_bytes(self, nome_arquivo: str | None = None, origem: int | None = None) -> requests.Response: ...
    def consultar_chaves_comentario(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def anexar_arquivos_base64_request(self, lista_arquivos: list[dict] | None = None, empresa: int | None = None, usuario: str | None = None) -> requests.Response: ...
    def retornar_arquivos_em_lista_bytes(self, empresa: str | None = None, identificador: str | None = None, listanomes_arquivos: list[dict] | None = None) -> requests.Response: ...
