from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Atendimento:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_atendimento(self, *args, **kwargs): ...
    def consultar_atendimento_detalhado_por_chave(self, *args, **kwargs): ...
    def consultar_atendimento_por_categorias_uau_web(self, *args, **kwargs): ...
    def consultar_atendimento_por_pessoa(self, *args, **kwargs): ...
    def consultar_atendimento_por_pessoa_comentario(self, *args, **kwargs): ...
    def consultar_categ_de_coment_ativas(self, *args, **kwargs): ...
    def consultar_categoria_atendimento_web(self, *args, **kwargs): ...
    def consultar_configuracao_atendimento_uauweb(self, *args, **kwargs): ...
    def consultar_data_prevista_de_termino_atendimento(self, *args, **kwargs): ...
    def consultar_empreendimentos_cliente(self, *args, **kwargs): ...
    def consultar_numero_vinculo_categoria_de_comentario_com_work_flow(self, *args, **kwargs): ...
    def consultar_numero_work_flow_vinculado(self, *args, **kwargs): ...
    def consultar_pendencia(self, *args, **kwargs): ...
    def consultar_pendencia_observacao(self, *args, **kwargs): ...
    def consultar_pendencias_por_numero_vinculo(self, *args, **kwargs): ...
    def consultar_unidades_do_empreendimento_cliente(self, *args, **kwargs): ...
    def gerar_atendimento_por_chat_online_cliente(self, *args, **kwargs): ...
    def gerar_pendencia(self, *args, **kwargs): ...
    def gravar_atendimento(self, *args, **kwargs): ...
    def vincular_arquivo_ao_atendimento(self, *args, **kwargs): ...
