import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Atendimento:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def gerar_pendencia(self, usuariouau_destino: str | None = None, data_prevista: datetime | None = None, data_aviso: datetime | None = None, hora_aviso: datetime | None = None, mensagem: str | None = None, geraremail_interno: bool | None = None, gerar_email_externo: bool | None = None, gerar_aviso: bool | None = None, categoria: str | None = None) -> requests.Response: ...
    def gravar_atendimento(self, atendimento: dict | None = None) -> requests.Response: ...
    def consultar_pendencia(self, numero: int | None = None, data_lancamento: datetime | None = None, responsavel_resolucao: str | None = None) -> requests.Response: ...
    def consultar_atendimento(self, codigo_atendimento: int | None = None) -> requests.Response: ...
    def consultar_categ_de_coment_ativas(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def consultar_pendencia_observacao(self, numero_pendencia: int | None = None, dataquando_lancou: datetime | None = None, usuario_resolve: str | None = None) -> requests.Response: ...
    def vincular_arquivo_ao_atendimento(self, arquivo: str | None = None, nome_arquivo: str | None = None, num_atendimento: int | None = None, usuario: str | None = None) -> requests.Response: ...
    def consultar_atendimento_por_pessoa(self, codigo_pessoa: int | None = None) -> requests.Response: ...
    def consultar_empreendimentos_cliente(self, cod_pessoa: int | None = None) -> requests.Response: ...
    def consultar_categoria_atendimento_web(self, tipo_atend: str | None = None) -> requests.Response: ...
    def consultar_numero_work_flow_vinculado(self, numerovinculo_workflow: int | None = None, empresa: int | None = None, obra: str | None = None) -> requests.Response: ...
    def consultar_pendencias_por_numero_vinculo(self, numero_vinculo: int | None = None) -> requests.Response: ...
    def gerar_atendimento_por_chat_online_cliente(self, dados_atendimento: dict | None = None) -> requests.Response: ...
    def consultar_atendimento_detalhado_por_chave(self, codigo_atendimento: int | None = None) -> requests.Response: ...
    def consultar_configuracao_atendimento_uauweb(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def consultar_atendimento_por_categorias_uau_web(self, codigo_pessoa: int | None = None) -> requests.Response: ...
    def consultar_atendimento_por_pessoa_comentario(self, codigo_pessoa: int | None = None, lista_categoria: list[dict] | None = None, periodo_incio: datetime | None = None, periodo_fim: datetime | None = None) -> requests.Response: ...
    def consultar_unidades_do_empreendimento_cliente(self, obra: str | None = None, empresa: int | None = None, cod_pessoa: int | None = None) -> requests.Response: ...
    def consultar_data_prevista_de_termino_atendimento(self, numerovinculo_workflow: int | None = None, numero_workflow: int | None = None) -> requests.Response: ...
    def consultar_numero_vinculo_categoria_de_comentario_com_work_flow(self, codigo_categoria: str | None = None) -> requests.Response: ...
