import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Autenticador:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def logout_usuario(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def autenticar_usuario(self, login: str | None = None, senha: str | None = None, usuariouau_site: str | None = None) -> requests.Response: ...
    def autenticar_usuario_app(self, login: str | None = None, senha: str | None = None, usuariouau_site: str | None = None) -> requests.Response: ...
    def verifica_usuario_logado(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def consultar_dados_usr_logado(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def autentificar_usuario_titanium(self, usuario: str | None = None, senha: str | None = None) -> requests.Response: ...
    def autenticar_usuario_corporativo(self, login_ad: str | None = None, senha: str | None = None, login_uau: str | None = None) -> requests.Response: ...
