from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Autenticador:
    def __init__(self, *args, **kwargs) -> None: ...
    def autenticar_usuario(self, *args, **kwargs): ...
    def autenticar_usuario_app(self, *args, **kwargs): ...
    def autenticar_usuario_corporativo(self, *args, **kwargs): ...
    def autentificar_usuario_titanium(self, *args, **kwargs): ...
    def consultar_dados_usr_logado(self, *args, **kwargs): ...
    def logout_usuario(self, *args, **kwargs): ...
    def verifica_usuario_logado(self, *args, **kwargs): ...
