from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class BoletoServices:
    def __init__(self, *args, **kwargs) -> None: ...
    def alterar_data_vencimento(self, *args, **kwargs): ...
    def consultar_boletos_do_cliente(self, *args, **kwargs): ...
    def consultar_boletos_reimpressao(self, *args, **kwargs): ...
    def consultar_dados_do_boleto(self, *args, **kwargs): ...
    def consultar_status_boleto(self, *args, **kwargs): ...
    def gerar_pdfboleto(self, *args, **kwargs): ...
    def gerar_pdfcarne(self, *args, **kwargs): ...
    def obter_codigo_de_barras(self, *args, **kwargs): ...
    def obter_linha_digitavel(self, *args, **kwargs): ...
    def obter_mensagem_do_boleto(self, *args, **kwargs): ...
