import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class BoletoServices:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def gerar_pdfcarne(self, filtro_chaves_boleto: list[dict] | None = None, filtro_venda_remessa: dict | None = None, carne_tres_boletos_pagina_na_vertical: bool | None = None, carne_dois_boletos_pagina_na_horizontal: bool | None = None) -> requests.Response: ...
    def gerar_pdfboleto(self, cod_banco: int | None = None, seu_numero: int | None = None, ocultar_dados_pessoais: bool | None = None) -> requests.Response: ...
    def obter_codigo_de_barras(self, cod_banco: str | None = None, seu_numero: str | None = None, data_venc: datetime | None = None, valor_nominal: int | None = None, campo_livre: str | None = None) -> requests.Response: ...
    def obter_linha_digitavel(self, codigode_barras: str | None = None) -> requests.Response: ...
    def alterar_data_vencimento(self, seu_numero: int | None = None, cod_banco: int | None = None, cod_empresa: int | None = None, nova_data_venc: datetime | None = None) -> requests.Response: ...
    def consultar_status_boleto(self, codigo_banco: int | None = None, seu_numero: int | None = None) -> requests.Response: ...
    def obter_mensagem_do_boleto(self, seu_numero: int | None = None, cod_banco: int | None = None, cod_empresa: int | None = None, instrucao: str | None = None, carteira: str | None = None) -> requests.Response: ...
    def consultar_dados_do_boleto(self, cod_banco: str | None = None, seu_numero: str | None = None) -> requests.Response: ...
    def consultar_boletos_do_cliente(self, cod_pessoa: int | None = None, nao_mostra_boleto_vencido: bool | None = None, usuario: str | None = None, tipo_usuario: int | None = None) -> requests.Response: ...
    def consultar_boletos_reimpressao(self, empresa: int | None = None, obra: str | None = None, num_venda: int | None = None, naomostraboleto_vencido: bool | None = None, mostrar_apenas_ultimo_boleto: bool | None = None) -> requests.Response: ...
