from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class ChavePix:
    def __init__(self, *args, **kwargs) -> None: ...
    def atualizar(self, *args, **kwargs): ...
    def by_cpfcnpj(self, *args, **kwargs): ...
    def cadastrar(self, *args, **kwargs): ...
    def deletar(self, *args, **kwargs): ...
