import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class ChavePix:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def by_cpfcnpj(self, cpf_cnpj: str, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def deletar(self, cpf_cnpj: str | None = None, chave_pix: str | None = None, tipo_chave_pix: int | None = None) -> requests.Response: ...
    def atualizar(self, cpf_cnpj: str | None = None, chave_pix: str | None = None, tipo_chave_pix: int | None = None, chave_pix_padrao: int | None = None, ativo_inativo: int | None = None) -> requests.Response: ...
    def cadastrar(self, cpf_cnpj: str | None = None, chave_pix: str | None = None, tipo_chave_pix: int | None = None, chave_pix_padrao: int | None = None, ativo_inativo: int | None = None) -> requests.Response: ...
