import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class CobrancaPix:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def pix_por_parcelas(self, parameters: list[dict] | None = None) -> requests.Response: ...
    def reimpressao_pix(self, tx_id: str | None = None) -> requests.Response: ...
    def consultar_pix_status(self, parameters: list[dict] | None = None) -> requests.Response: ...
    def gerar_cobranca_venda(self, data_de_calculo: datetime | None = None, antecipar: bool | None = None, usar_padrao_pix_avulso: bool | None = None, agrupar_parcelas: bool | None = None, padrao_cobranca: int | None = None, parcelas: list[dict] | None = None) -> requests.Response: ...
    def gerar_cobranca_proposta(self, data_de_calculo: datetime | None = None, antecipar: bool | None = None, usar_padrao_pix_avulso: bool | None = None, agrupar_parcelas: bool | None = None, padrao_cobranca: int | None = None, parcelas: list[dict] | None = None) -> requests.Response: ...
