from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class CobrancaPix:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_pix_status(self, *args, **kwargs): ...
    def gerar_cobranca_proposta(self, *args, **kwargs): ...
    def gerar_cobranca_venda(self, *args, **kwargs): ...
    def pix_por_parcelas(self, *args, **kwargs): ...
    def reimpressao_pix(self, *args, **kwargs): ...
