from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Comissao:
    def __init__(self, *args, **kwargs) -> None: ...
    def atualizar_status_comissao(self, *args, **kwargs): ...
    def consultar_estrutura_comissao(self, *args, **kwargs): ...
    def consultar_modelo_comissao(self, *args, **kwargs): ...
    def consultar_vendedores(self, *args, **kwargs): ...
