import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Comissao:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def consultar_vendedores(self, codigo_modelo_comissao: int | None = None) -> requests.Response: ...
    def atualizar_status_comissao(self, parameters: list[dict] | None = None) -> requests.Response: ...
    def consultar_modelo_comissao(self, codigo_empresa: int | None = None, codigo_obra: str | None = None, codigo_vendedor: int | None = None, data_venda: str | None = None, qtde_parcelas: int | None = None, lista_unidades: list[dict] | None = None) -> requests.Response: ...
    def consultar_estrutura_comissao(self, empresa: int | None = None, obra: str | None = None, codigo_vendedor: int | None = None, codigo_hierarquia: int | None = None, numero_comissao: int | None = None, valor_comissao: int | None = None, produtos: list[dict] | None = None) -> requests.Response: ...
