from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Composicoes:
    def __init__(self, *args, **kwargs) -> None: ...
    def alterar_insumo_composicoes_geral(self, *args, **kwargs): ...
    def alterar_insumo_composicoes_geral_pesada(self, *args, **kwargs): ...
    def atualizar_composicoes(self, *args, **kwargs): ...
    def consultar_composicoes_com_filtro_livre(self, *args, **kwargs): ...
    def consultar_composicoes_por_chave(self, *args, **kwargs): ...
    def consultar_composicoes_por_descricao(self, *args, **kwargs): ...
    def consultar_insumos_da_composicao(self, *args, **kwargs): ...
    def consultar_todas_composicoes(self, *args, **kwargs): ...
    def inserir_composicoes(self, *args, **kwargs): ...
    def inserir_insumo_composicoes_geral(self, *args, **kwargs): ...
    def inserir_insumo_composicoes_geral_pesada(self, *args, **kwargs): ...
