from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class ConfigGerais:
    def __init__(self, *args, **kwargs) -> None: ...
    def obter_configuracao_de_casas_decimais(self, *args, **kwargs): ...
    def retornar_versao_bd(self, *args, **kwargs): ...
    def retornar_versao_ws(self, *args, **kwargs): ...
