from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class ContratoMaterialServico:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_contrato_por_chave(self, *args, **kwargs): ...
    def consultar_contrato_por_fornecedor(self, *args, **kwargs): ...
    def consultar_contrato_por_servico_material(self, *args, **kwargs): ...
    def consultar_contratos_itens_vinculado_orcamento(self, *args, **kwargs): ...
    def consultar_itens_contrato(self, *args, **kwargs): ...
    def consultar_itens_vinculo_orcamento_servico(self, *args, **kwargs): ...
    def consultar_itens_vinculo_planejamento_servico(self, *args, **kwargs): ...
    def consultar_saldo_reajustado_por_item_contrato(self, *args, **kwargs): ...
