import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class ContratoMaterialServico:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def consultar_itens_contrato(self, empresa: int | None = None, contrato: int | None = None) -> requests.Response: ...
    def consultar_contrato_por_chave(self, empresa: int | None = None, contrato: int | None = None) -> requests.Response: ...
    def consultar_contrato_por_fornecedor(self, fornecedor: int | None = None) -> requests.Response: ...
    def consultar_contrato_por_servico_material(self, empresa: int | None = None, servico_material: str | None = None) -> requests.Response: ...
    def consultar_itens_vinculo_orcamento_servico(self, empresa: int | None = None, obra: str | None = None, item: str | None = None, servico: str | None = None, orcamento: int | None = None, somente_contratos_aprovados: bool | None = None) -> requests.Response: ...
    def consultar_saldo_reajustado_por_item_contrato(self, empresa: int | None = None, obra: str | None = None, contratos: list[dict] | None = None, situacoes: list[dict] | None = None) -> requests.Response: ...
    def consultar_itens_vinculo_planejamento_servico(self, empresa: int | None = None, obra: str | None = None, item: str | None = None, servico: str | None = None, produto: int | None = None, contrato: int | None = None) -> requests.Response: ...
    def consultar_contratos_itens_vinculado_orcamento(self, empresa: int | None = None, obra: str | None = None, orcamento: int | None = None, somente_contratos_aprovados: bool | None = None) -> requests.Response: ...
