from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Contabil:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_contas_contabeis(self, *args, **kwargs): ...
    def consultar_saldo_de_contas(self, *args, **kwargs): ...
