from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Cotacao:
    def __init__(self, *args, **kwargs) -> None: ...
    def adicionar_fornecedor_cotacao(self, *args, **kwargs): ...
    def aprovar_confirmacao_cotacao_por_obra(self, *args, **kwargs): ...
    def aprovar_simulacoes_compra(self, *args, **kwargs): ...
    def atualizar_condicao_pagamento_entrega(self, *args, **kwargs): ...
    def atualizar_item_cotacao(self, *args, **kwargs): ...
    def buscar_cotacao_aberta_fornecedor(self, *args, **kwargs): ...
    def buscar_itens_cotacao_fornecedor(self, *args, **kwargs): ...
    def consultar_aprovacao_da_cotacao_por_obra(self, *args, **kwargs): ...
    def consultar_cotacoes_confirmacao_pendente(self, *args, **kwargs): ...
    def consultar_itens_cotacao_por_obra(self, *args, **kwargs): ...
    def consultar_justificativas_aprovacao_fora_sequencia(self, *args, **kwargs): ...
    def consultar_quantidade_cotacao_pendente_por_obra(self, *args, **kwargs): ...
    def consultar_quantidade_cotacao_pendente_por_obra_mob(self, *args, **kwargs): ...
    def conta_cotacoes_aprov_mob(self, *args, **kwargs): ...
    def inserir_altera_coment_forn_frete(self, *args, **kwargs): ...
    def remover_aprovacao_simulacoes_compra(self, *args, **kwargs): ...
    def reprovar_confirmacoes_cotacao_por_obra(self, *args, **kwargs): ...
