import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Cotacao:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def atualizar_item_cotacao(self, lista_itens_cotacao: list[dict] | None = None) -> requests.Response: ...
    def conta_cotacoes_aprov_mob(self, usuario: str | None = None) -> requests.Response: ...
    def aprovar_simulacoes_compra(self, simulacoes: list[dict] | None = None) -> requests.Response: ...
    def adicionar_fornecedor_cotacao(self, cod_fornecedor: int | None = None, cnpj_fornecedor: str | None = None, numero_cotacao: int | None = None, numero_cotacao_geral: int | None = None, empresa: int | None = None) -> requests.Response: ...
    def buscar_itens_cotacao_fornecedor(self, empresa: int | None = None, cotacao: int | None = None, fornecedor: int | None = None, origem: int | None = None) -> requests.Response: ...
    def consultar_itens_cotacao_por_obra(self, empresa: int | None = None, obra: str | None = None, cotacao: int | None = None) -> requests.Response: ...
    def buscar_cotacao_aberta_fornecedor(self, cnpj: str | None = None) -> requests.Response: ...
    def aprovar_confirmacao_cotacao_por_obra(self, lista_confirmar_aprovacao_cotacao: list[dict] | None = None) -> requests.Response: ...
    def remover_aprovacao_simulacoes_compra(self, simulacoes: list[dict] | None = None) -> requests.Response: ...
    def atualizar_condicao_pagamento_entrega(self, empresa: int | None = None, cotacao: int | None = None, numero_cotacao_geral: int | None = None, fornecedor: int | None = None, dias_entrega: int | None = None, quantidade_entrega: int | None = None, intervalo_entrega: int | None = None, dias_pagamento: int | None = None, quantidade_parcela: int | None = None, intervalo_parcela: int | None = None, tipo_frete: int | None = None, tipo_pagamento: int | None = None, condicao_pagamento: str | None = None) -> requests.Response: ...
    def consultar_aprovacao_da_cotacao_por_obra(self, codigo_empresa: int | None = None, codigo_obra: str | None = None, numero_simulacao: int | None = None, numero_cotacao: int | None = None) -> requests.Response: ...
    def reprovar_confirmacoes_cotacao_por_obra(self, confirmacoes_cotacao: list[dict] | None = None, justificativa_reprovacao: str | None = None) -> requests.Response: ...
    def consultar_cotacoes_confirmacao_pendente(self, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None, lista_emp_obras: list[dict] | None = None, cotacao: int | None = None) -> requests.Response: ...
    def consultar_quantidade_cotacao_pendente_por_obra(self, login_usuario: str | None = None, codigo_departamento: str | None = None, codigo_cargo: str | None = None, lista_emp_obras: list[dict] | None = None) -> requests.Response: ...
    def consultar_quantidade_cotacao_pendente_por_obra_mob(self, login_usuario: str | None = None, codigo_departamento: str | None = None, codigo_cargo: str | None = None, lista_emp_obras: list[dict] | None = None) -> requests.Response: ...
    def consultar_justificativas_aprovacao_fora_sequencia(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def inserir_altera_coment_forn_frete(self, empresa: int | None = None, codigo_fornecedor: int | None = None, cotacao: int | None = None, cond_pagto: int | None = None, tipo_coment: int | None = None, efet_pgto_parc: int | None = None, dtvenc_ini: str | None = None, qtde_parc: int | None = None, intev_parc: int | None = None, obs_pgto: str | None = None, obs_entrega: str | None = None, tipo_pgto: int | None = None, tem_frete: int | None = None, diaini_venc: int | None = None, freteqtde_ent: int | None = None, interv_ent: int | None = None, dias_entrega: int | None = None) -> requests.Response: ...
