from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class DocumentosDigitaisIntegracao:
    def __init__(self, *args, **kwargs) -> None: ...
    def consulta_documentos_digitais_ativos(self, *args, **kwargs): ...
    def consultar_assinaturas_enviadas(self, *args, **kwargs): ...
    def consultar_documentos_enviados(self, *args, **kwargs): ...
    def consultar_envelope_documentos_codigo_externo(self, *args, **kwargs): ...
    def enviar_envelope_de_documento(self, *args, **kwargs): ...
