import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class DocumentosDigitaisIntegracao:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def enviar_envelope_de_documento(self, lista_de_pessoas: list[dict] | None = None, lista_de_documentos: list[dict] | None = None, mensagem: str | None = None, codigo_do_sistema: int | None = None) -> requests.Response: ...
    def consultar_documentos_enviados(self, numero_do_envelope: int | None = None) -> requests.Response: ...
    def consultar_assinaturas_enviadas(self, numero_do_envelope: int | None = None) -> requests.Response: ...
    def consulta_documentos_digitais_ativos(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def consultar_envelope_documentos_codigo_externo(self, envelope_id: str | None = None) -> requests.Response: ...
