from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Empresa:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_dados_basicos_empresas_por_filtro(self, *args, **kwargs): ...
    def consultar_empresa(self, *args, **kwargs): ...
    def obter_empresas_ativas(self, *args, **kwargs): ...
