import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Empresa:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def consultar_empresa(self, codigo_empresa: int | None = None) -> requests.Response: ...
    def obter_empresas_ativas(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def consultar_dados_basicos_empresas_por_filtro(self, empresa: int | None = None, descricao_empresa: str | None = None, cnpj: str | None = None, limitar_retorno_em: int | None = None) -> requests.Response: ...
