import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Espelho:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def alterar_status_unidade(self, codigo_empresa: int | None = None, codigo_produto: int | None = None, numero_personalizacao: int | None = None, novo_status_unidade: int | None = None, motivo_alteracao: str | None = None, categoria_status_personalizacao: int | None = None) -> requests.Response: ...
    def consultar_espelhos_venda(self, usuario_logado: str | None = None) -> requests.Response: ...
    def retornar_menor_preco_person(self, tipo_contrato: int | None = None, cod_produto: int | None = None, cod_categ_preco: str | None = None, numero_person: int | None = None, empresa: int | None = None, data_categ_preco_produto: datetime | None = None, porc_preco_minimo: int | None = None) -> requests.Response: ...
    def atualizar_campos_customizados(self, campos_custom: dict | None = None) -> requests.Response: ...
    def consultar_unidade_per_por_chave(self, codigo_empresa: int | None = None, codigo_produto: int | None = None, numero_personalizacao: int | None = None) -> requests.Response: ...
    def busca_unidades_de_acordo_com_where(self, where: str | None = None, retorna_venda: bool | None = None) -> requests.Response: ...
    def alterar_data_entrega_chaves_unidade(self, codigo_empresa: int | None = None, codigo_produto: int | None = None, numero_personalizacao: int | None = None, data_entrega_chaves: datetime | None = None, observacao: str | None = None) -> requests.Response: ...
    def consultar_personalizacoes_com_precos(self, usuario: str | None = None, empresa: int | None = None, num_produto: int | None = None, cod_obra: str | None = None, num_personalizacao: int | None = None, consultarapenasnao_vendidos: bool | None = None, tipo_contrato: int | None = None, datatabela_preco: datetime | None = None, campos_person: str | None = None, status_person: str | None = None, num_espelho: int | None = None, tipocontrato_grafico: int | None = None) -> requests.Response: ...
    def busca_unidades_de_acordo_com_where_detalhado(self, where: str | None = None, retorna_venda: bool | None = None, data_tabela_preco: datetime | None = None) -> requests.Response: ...
