from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Espelho:
    def __init__(self, *args, **kwargs) -> None: ...
    def alterar_data_entrega_chaves_unidade(self, *args, **kwargs): ...
    def alterar_status_unidade(self, *args, **kwargs): ...
    def atualizar_campos_customizados(self, *args, **kwargs): ...
    def busca_unidades_de_acordo_com_where(self, *args, **kwargs): ...
    def busca_unidades_de_acordo_com_where_detalhado(self, *args, **kwargs): ...
    def consultar_espelhos_venda(self, *args, **kwargs): ...
    def consultar_personalizacoes_com_precos(self, *args, **kwargs): ...
    def consultar_unidade_per_por_chave(self, *args, **kwargs): ...
    def retornar_menor_preco_person(self, *args, **kwargs): ...
