import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Estrutura:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def excluir_estrutura(self, codigo_estrutura: int | None = None, sequencia: str | None = None) -> requests.Response: ...
    def inserir_estrutura(self, descricao: str | None = None) -> requests.Response: ...
    def excluir_item_de_estrutura(self, codigo_item: str | None = None) -> requests.Response: ...
    def inserir_item_de_estrutura(self, codigo_item: str | None = None, descricao_item: str | None = None) -> requests.Response: ...
    def inserir_item_na_estrutura(self, codigo_estrutura: int | None = None, tipo_estrutura: int | None = None, sequencia: str | None = None, codigo_item: str | None = None) -> requests.Response: ...
