from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Estrutura:
    def __init__(self, *args, **kwargs) -> None: ...
    def excluir_estrutura(self, *args, **kwargs): ...
    def excluir_item_de_estrutura(self, *args, **kwargs): ...
    def inserir_estrutura(self, *args, **kwargs): ...
    def inserir_item_de_estrutura(self, *args, **kwargs): ...
    def inserir_item_na_estrutura(self, *args, **kwargs): ...
