from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Eventos:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_chaves_log_de_eventos(self, *args, **kwargs): ...
    def consultar_log_eventos(self, *args, **kwargs): ...
