from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class ExtratoDoCliente:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_dados_demonstrativo_pagto_cliente(self, *args, **kwargs): ...
    def consultar_saldo_cessoes_direito_anteriores(self, *args, **kwargs): ...
    def gerar_pdfextrato_cliente(self, *args, **kwargs): ...
    def gerar_pdfextrato_cliente_v2(self, *args, **kwargs): ...
