import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class ExtratoDoCliente:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def gerar_pdfextrato_cliente(self, empresa: int | None = None, obra: str | None = None, num_venda: int | None = None, tipo_ordenacao: int | None = None, valor_antecipado: bool | None = None, data_prorrogacao: bool | None = None, ocultar_personalizacao: bool | None = None, ocultar_usuario: bool | None = None, data_calculo: datetime | None = None, residuo_ira_compor_valor_total: bool | None = None) -> requests.Response: ...
    def gerar_pdfextrato_cliente_v2(self, empresa: int | None = None, obra: str | None = None, num_venda: int | None = None, tipo_ordenacao: int | None = None, valor_antecipado: bool | None = None, data_prorrogacao: bool | None = None, ocultar_personalizacao: bool | None = None, ocultar_usuario: bool | None = None, data_calculo: datetime | None = None, residuo_ira_compor_valor_total: bool | None = None) -> requests.Response: ...
    def consultar_saldo_cessoes_direito_anteriores(self, empresa: int | None = None, obra: str | None = None, num_venda: int | None = None) -> requests.Response: ...
    def consultar_dados_demonstrativo_pagto_cliente(self, empresa: int | None = None, obra: str | None = None, num_venda: int | None = None, tipos_parc: str | None = None, tipo_ordenacao: int | None = None, mostrara_pagas: bool | None = None, princ_juros: bool | None = None, descontopor_adiantamento: bool | None = None, valor_antecipado: bool | None = None, nome_fantasia: bool | None = None, ocultapref_custas: bool | None = None, data_calculo: datetime | None = None, exibir_data_deposito: bool | None = None) -> requests.Response: ...
