from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Fiscal:
    def __init__(self, *args, **kwargs) -> None: ...
    def buscar_caps(self, *args, **kwargs): ...
    def buscar_codigo_servico_fiscal(self, *args, **kwargs): ...
    def importar_lancamentos_contabeis(self, *args, **kwargs): ...
    def importar_lancamentos_fiscais(self, *args, **kwargs): ...
