import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Fiscal:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def buscar_caps(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def buscar_codigo_servico_fiscal(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def importar_lancamentos_fiscais(self, dadoslacamentos_xml: str | None = None) -> requests.Response: ...
    def importar_lancamentos_contabeis(self, dadoslacamentos_xml: str | None = None) -> requests.Response: ...
