from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Folha:
    def __init__(self, *args, **kwargs) -> None: ...
    def gravar_alocacao_mao_obra(self, *args, **kwargs): ...
    def gravar_movimentacao_mensal_obra(self, *args, **kwargs): ...
