from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class InsumosGeral:
    def __init__(self, *args, **kwargs) -> None: ...
    def atualizar_insumos_geral(self, *args, **kwargs): ...
    def consultar_insumos_geral(self, *args, **kwargs): ...
    def consultar_insumos_geral_por_chave(self, *args, **kwargs): ...
    def consultar_insumos_geral_por_descricao(self, *args, **kwargs): ...
    def inserir_insumos_geral(self, *args, **kwargs): ...
