from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class ListaPrecoReferencia:
    def __init__(self, *args, **kwargs) -> None: ...
    def atualizar_item_fornecedor(self, *args, **kwargs): ...
    def consultar_lista_preco_referencia(self, *args, **kwargs): ...
    def inserir_fornecedores(self, *args, **kwargs): ...
