import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class ListaPrecoReferencia:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def inserir_fornecedores(self, numero_lista: int | None = None, codigo_fornecedor: int | None = None, cpfcnpj: str | None = None, valor_minimo_pedfob: int | None = None, valor_minimo_pedcif: int | None = None, data_inicio: datetime | None = None, data_termino: datetime | None = None, contato: str | None = None, itens_por_fornecedor: list[dict] | None = None) -> requests.Response: ...
    def atualizar_item_fornecedor(self, numero_lista: int | None = None, codigo_fornecedor: int | None = None, cpfcnpj: str | None = None, valor_minimo_pedfob: int | None = None, valor_minimo_pedcif: int | None = None, data_inicio: datetime | None = None, data_termino: datetime | None = None, contato: str | None = None, itens_por_fornecedor: list[dict] | None = None) -> requests.Response: ...
    def consultar_lista_preco_referencia(self, numero_lista: int | None = None, data_validade: datetime | None = None, status: int | None = None, fornecedorcnpj: str | None = None, fornecedor_codigo: int | None = None) -> requests.Response: ...
