import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Medicao:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def manter_medicao(self, empresa: int | None = None, numero_contrato: int | None = None, numero_medicao: int | None = None, codigo_fornecedor: int | None = None, cnpj_fornecedor: str | None = None, num_cidade_prestacao_serv: int | None = None, observacao: str | None = None, ultima_medicao: int | None = None, data_base: datetime | None = None, usr_cadastro: str | None = None, descontos_medicao: list[dict] | None = None, itens: list[dict] | None = None, adiantamentos: list[dict] | None = None) -> requests.Response: ...
    def excluir_medicao(self, empresa: int | None = None, contrato: int | None = None, numero_medicao: int | None = None) -> requests.Response: ...
    def consultar_medicao(self, empresa: int | None = None, contrato: int | None = None, medicao: int | None = None) -> requests.Response: ...
    def consultar_itens_medicao(self, empresa: int | None = None, contrato: int | None = None, medicao: int | None = None) -> requests.Response: ...
    def aprovar_medicoes_contrato(self, medicoes: list[dict] | None = None) -> requests.Response: ...
    def consultar_boletim_medicao(self, empresa: int | None = None, contrato: int | None = None, avanco_fisico: bool | None = None, medicao: int | None = None) -> requests.Response: ...
    def consultar_medicao_completa(self, empresa: int | None = None, contrato: int | None = None, medicao: int | None = None, cnpj_contratado: str | None = None, cnpj_fornecedor: str | None = None, data_inicial: datetime | None = None, data_final: datetime | None = None) -> requests.Response: ...
    def consultar_medicao_por_serv_mat(self, empresa: int | None = None, serv_mat: str | None = None) -> requests.Response: ...
    def consultar_medicoes_por_status(self, status_med: int | None = None, login_usu: str | None = None) -> requests.Response: ...
    def validar_cnpjao_gravar_medicao(self) -> requests.Response: ...
    def consultar_medicao_por_contrato(self, empresa: int | None = None, contrato: int | None = None) -> requests.Response: ...
    def consultar_itens_medicao_por_medicao(self, empresa: int | None = None, contrato: int | None = None, medicao: int | None = None) -> requests.Response: ...
    def consultar_itens_medicao_por_serv_mat(self, empresa: int | None = None, serv_mat: str | None = None) -> requests.Response: ...
    def consultar_itens_medicao_por_contrato(self, empresa: int | None = None, contrato: int | None = None) -> requests.Response: ...
    def consultar_itens_medicao_por_item_contrato(self, empresa: int | None = None, contrato: int | None = None, medicao: int | None = None, item_contrato: int | None = None) -> requests.Response: ...
