from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Medicao:
    def __init__(self, *args, **kwargs) -> None: ...
    def aprovar_medicoes_contrato(self, *args, **kwargs): ...
    def consultar_boletim_medicao(self, *args, **kwargs): ...
    def consultar_itens_medicao(self, *args, **kwargs): ...
    def consultar_itens_medicao_por_contrato(self, *args, **kwargs): ...
    def consultar_itens_medicao_por_item_contrato(self, *args, **kwargs): ...
    def consultar_itens_medicao_por_medicao(self, *args, **kwargs): ...
    def consultar_itens_medicao_por_serv_mat(self, *args, **kwargs): ...
    def consultar_medicao(self, *args, **kwargs): ...
    def consultar_medicao_completa(self, *args, **kwargs): ...
    def consultar_medicao_por_contrato(self, *args, **kwargs): ...
    def consultar_medicao_por_serv_mat(self, *args, **kwargs): ...
    def consultar_medicoes_por_status(self, *args, **kwargs): ...
    def excluir_medicao(self, *args, **kwargs): ...
    def manter_medicao(self, *args, **kwargs): ...
    def validar_cnpjao_gravar_medicao(self, *args, **kwargs): ...
