from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class ModeloVenda:
    def __init__(self, *args, **kwargs) -> None: ...
    def buscar_plano_indexador(self, *args, **kwargs): ...
    def consultar_modelo_de_venda(self, *args, **kwargs): ...
    def consultar_modelo_de_venda_seguro_por_chave(self, *args, **kwargs): ...
    def consultar_modelo_venda(self, *args, **kwargs): ...
    def consultar_parcelas_modelo_venda(self, *args, **kwargs): ...
    def gerar_parcelas_proposta(self, *args, **kwargs): ...
    def montar_modelo_renegociacao(self, *args, **kwargs): ...
