import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class ModeloVenda:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def buscar_plano_indexador(self, nummodelo_venda: int | None = None) -> requests.Response: ...
    def consultar_modelo_venda(self, cod_modelo_venda: int | None = None) -> requests.Response: ...
    def gerar_parcelas_proposta(self, parametromodelovenda: list[dict] | None = None, codigo_empresa: int | None = None, codigo_obra: str | None = None, redistribuir_valor: bool | None = None, utilizar_cap: bool | None = None, tipo_venda: int | None = None) -> requests.Response: ...
    def consultar_modelo_de_venda(self, obra: str | None = None, empresa: int | None = None, nummodelo_venda: int | None = None, eat_inat: int | None = None, campos_retornados: str | None = None, tipo: int | None = None) -> requests.Response: ...
    def montar_modelo_renegociacao(self, cod_modelo_venda: int | None = None, empresa: int | None = None, obra: str | None = None, num_venda: int | None = None, valor_reneg_contrato: int | None = None, valor_reneg_custas: int | None = None, valor_reneg_seguromip: int | None = None, valor_reneg_segurodfi: int | None = None) -> requests.Response: ...
    def consultar_parcelas_modelo_venda(self, nummodelo_venda: int | None = None) -> requests.Response: ...
    def consultar_modelo_de_venda_seguro_por_chave(self, nummodelo_venda: int | None = None) -> requests.Response: ...
