from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class NotasFiscais:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_nfentrada(self, *args, **kwargs): ...
    def salvar_arquivo_xmlnotafiscal_entrada(self, *args, **kwargs): ...
