from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Obras:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_obra_por_chave(self, *args, **kwargs): ...
    def obter_meses_abertos_por_empresa_obra(self, *args, **kwargs): ...
    def obter_obras_ativas(self, *args, **kwargs): ...
