import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Obras:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def obter_obras_ativas(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def consultar_obra_por_chave(self, empresa: int | None = None, obra: str | None = None) -> requests.Response: ...
    def obter_meses_abertos_por_empresa_obra(self, empresa_obra: str | None = None) -> requests.Response: ...
