from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Orcamento:
    def __init__(self, *args, **kwargs) -> None: ...
    def alterar_insumo_orcamento(self, *args, **kwargs): ...
    def alterar_planilha_cronograma(self, *args, **kwargs): ...
    def alterar_servico_orcamento(self, *args, **kwargs): ...
    def atualizar_estrutura_servico_de_orcamento(self, *args, **kwargs): ...
    def consultar_estrutura_orca_por_chave(self, *args, **kwargs): ...
    def consultar_estrutura_orca_por_servico(self, *args, **kwargs): ...
    def consultar_insumos_por_chave(self, *args, **kwargs): ...
    def consultar_planilha_cronograma_por_chave(self, *args, **kwargs): ...
    def consultar_servico_orcado_desintegrado(self, *args, **kwargs): ...
    def consultar_servico_orcamento_por_chave(self, *args, **kwargs): ...
    def consultar_servico_orcamento_por_orcamento(self, *args, **kwargs): ...
    def excluir_estrutura_servico_de_orcamento(self, *args, **kwargs): ...
    def excluir_insumo_orcamento(self, *args, **kwargs): ...
    def excluir_planilha_cronograma(self, *args, **kwargs): ...
    def excluir_servico_orcamento(self, *args, **kwargs): ...
    def exportar_orcamento_estrutura(self, *args, **kwargs): ...
    def inserir_estrutura_servico_de_orcamento(self, *args, **kwargs): ...
    def inserir_insumo_orcamento(self, *args, **kwargs): ...
    def inserir_planilha_cronograma(self, *args, **kwargs): ...
    def inserir_servico_orcamento(self, *args, **kwargs): ...
