import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Orcamento:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def alterar_insumo_orcamento(self, empresa: int | None = None, obra: str | None = None, orcamento: int | None = None, composicao: str | None = None, insumo: str | None = None, usuario: str | None = None, quantidade: int | None = None, preco: int | None = None, tipo_insumo: int | None = None, encargo: int | None = None) -> requests.Response: ...
    def excluir_insumo_orcamento(self, empresa: int | None = None, obra: str | None = None, orcamento: int | None = None, composicao: str | None = None, insumo: str | None = None, usuario: str | None = None, quantidade: int | None = None, preco: int | None = None, tipo_insumo: int | None = None, encargo: int | None = None) -> requests.Response: ...
    def inserir_insumo_orcamento(self, insumos_orcamento: list[dict] | None = None) -> requests.Response: ...
    def alterar_servico_orcamento(self, usuario: str | None = None, quantidade: int | None = None, data_inicio: datetime | None = None, data_fim: datetime | None = None, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, cod_externo_integracao: str | None = None) -> requests.Response: ...
    def excluir_servico_orcamento(self, usuario: str | None = None, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, cod_externo_integracao: str | None = None) -> requests.Response: ...
    def inserir_servico_orcamento(self, servicos_orcamento: list[dict] | None = None) -> requests.Response: ...
    def consultar_insumos_por_chave(self, empresa: int | None = None, obra: str | None = None, orcamento: int | None = None, composicao: str | None = None) -> requests.Response: ...
    def alterar_planilha_cronograma(self, usuario: str | None = None, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, periodo: str | None = None, quantidade: int | None = None) -> requests.Response: ...
    def excluir_planilha_cronograma(self, usuario: str | None = None, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, periodo: str | None = None, quantidade: int | None = None) -> requests.Response: ...
    def inserir_planilha_cronograma(self, usuario: str | None = None, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, periodo: str | None = None, quantidade: int | None = None) -> requests.Response: ...
    def exportar_orcamento_estrutura(self, empresa: int | None = None, obra: str | None = None, orcamento: int | None = None) -> requests.Response: ...
    def consultar_estrutura_orca_por_chave(self, sequencia: str | None = None, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, cod_externo_integracao: str | None = None) -> requests.Response: ...
    def consultar_estrutura_orca_por_servico(self, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, cod_externo_integracao: str | None = None) -> requests.Response: ...
    def consultar_servico_orcamento_por_chave(self, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, cod_externo_integracao: str | None = None) -> requests.Response: ...
    def consultar_servico_orcado_desintegrado(self, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None) -> requests.Response: ...
    def excluir_estrutura_servico_de_orcamento(self, estruturas_de_servico_de_orcamento: list[dict] | None = None) -> requests.Response: ...
    def inserir_estrutura_servico_de_orcamento(self, estruturas_de_servico_de_orcamento: list[dict] | None = None) -> requests.Response: ...
    def consultar_planilha_cronograma_por_chave(self, usuario: str | None = None, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, item: str | None = None, servico: str | None = None, periodo: str | None = None) -> requests.Response: ...
    def atualizar_estrutura_servico_de_orcamento(self, estruturas_de_servico_de_orcamento: list[dict] | None = None) -> requests.Response: ...
    def consultar_servico_orcamento_por_orcamento(self, empresa: int | None = None, obra: str | None = None, num_orcamento: int | None = None, tipo_item: int | None = None) -> requests.Response: ...
