import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class PedidoCompra:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def aprovar_pedido_compra_servico_app(self, codigo_empresa: int | None = None, codigo_obra: str | None = None, servico: str | None = None, num_pedido: int | None = None, mensagem_retorno: str | None = None, departamento: str | None = None, cargo: str | None = None, cod_justificativa: int | None = None, obs_justificativa: str | None = None) -> requests.Response: ...
    def aprovar_pedido_compra_material_app(self, codigo_empresa: int | None = None, codigo_obra: str | None = None, insumo: str | None = None, item_ped: int | None = None, num_pedido: int | None = None, mensagem_retorno: str | None = None, departamento: str | None = None, cargo: str | None = None, cod_justificativa: int | None = None, obs_justificativa: str | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_servico(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_material(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_patrimonio(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_complemento(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_emergencial(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_adiantamento(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None, numero_contrato: int | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_regularizacao(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def confirmar_recebimento_ordem_compra_fornecedor(self, nome_fornecedor: str | None = None, codigo_empresa: int | None = None, codigo_obra: str | None = None, ordem_de_compra: int | None = None, tipo_resposta: int | None = None, observacao: str | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_servico_contrato(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_contrato_material(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_servico_complemento(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_servico_emergencial(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_servico_adiantamento(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None, numero_contrato: int | None = None) -> requests.Response: ...
    def gravar_pedido_de_compra_do_tipo_servico_regularizacao(self, dados_pedido: dict | None = None, lista_dados_item_pedido: list[dict] | None = None) -> requests.Response: ...
