from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class PedidoCompra:
    def __init__(self, *args, **kwargs) -> None: ...
    def aprovar_pedido_compra_material_app(self, *args, **kwargs): ...
    def aprovar_pedido_compra_servico_app(self, *args, **kwargs): ...
    def confirmar_recebimento_ordem_compra_fornecedor(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_adiantamento(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_complemento(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_contrato_material(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_emergencial(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_material(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_patrimonio(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_regularizacao(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_servico(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_servico_adiantamento(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_servico_complemento(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_servico_contrato(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_servico_emergencial(self, *args, **kwargs): ...
    def gravar_pedido_de_compra_do_tipo_servico_regularizacao(self, *args, **kwargs): ...
