import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Pessoas:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def gravar_pessoa(self, nao_validar_campos_obrigatorios: bool | None = None, info_pes: dict | None = None, info_pesfis: dict | None = None, infopes_jur: dict | None = None, dspes_tel_json: str | None = None, infopes_doc: dict | None = None, info_pesendereco_principal: dict | None = None, infopesendereco_cobranca: dict | None = None, infopesendereco_comercial: dict | None = None) -> requests.Response: ...
    def manter_telefone(self, numero: int | None = None, telefones: list[dict] | None = None) -> requests.Response: ...
    def excluir_telefone(self, numero: int | None = None, telefones: list[dict] | None = None) -> requests.Response: ...
    def consultar_unidades(self, codigo_pessoa: int | None = None, cpf_cnpj: str | None = None) -> requests.Response: ...
    def consultar_telefones(self, numero: int | None = None) -> requests.Response: ...
    def alterar_senha_cliente(self, codigo_cliente: int | None = None, senha: str | None = None) -> requests.Response: ...
    def gravar_conta_bancaria(self, codigo_pessoa: int | None = None, banco: int | None = None, conta: str | None = None, padrao: bool | None = None, tipo: int | None = None, agencia: str | None = None, nome_agencia: str | None = None, debito_automatico: bool | None = None) -> requests.Response: ...
    def consultar_tipo_endereco(self, codigo_pessoa: int | None = None) -> requests.Response: ...
    def criar_credenciais_uauweb(self, cpf: str | None = None, data_nascimento: datetime | None = None, login: str | None = None, senha: str | None = None, email: str | None = None) -> requests.Response: ...
    def consultar_pessoa_por_chave(self, codigo_pessoa: int | None = None) -> requests.Response: ...
    def consultar_contas_bancarias(self, codigo: str | None = None) -> requests.Response: ...
    def consultar_pessoas_com_venda(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def alterar_pessoa_acesso_portal(self, codigo_pessoa: int | None = None, login: str | None = None, senha: str | None = None, email: str | None = None) -> requests.Response: ...
    def consultar_pessoas_por_cpfcnpj(self, cpf_cnpj: str | None = None, status: int | None = None) -> requests.Response: ...
    def excluir_banco_econta_por_chave(self, codigo_pessoa: int | None = None, banco: int | None = None, conta: str | None = None, agencia: str | None = None) -> requests.Response: ...
    def recuperar_credenciais_uauweb(self, login: str | None = None, email: str | None = None) -> requests.Response: ...
    def consultar_pessoas_por_condicao(self, condicao_consultar_pessoa: str | None = None) -> requests.Response: ...
    def importar_dados_pessoas_para_uau(self, xml: str | None = None) -> requests.Response: ...
    def consultar_telefone_pes_por_chave(self, codigo_pessoa: int | None = None) -> requests.Response: ...
    def consultar_endereco_pessoas_por_chave(self, codigo_pessoa: int | None = None, tipo_endereco: int | None = None) -> requests.Response: ...
    def consultar_pessoas_funcionarios_ativos(self, page: int | None = None, page_size: int | None = None, search_text: str | None = None) -> requests.Response: ...
    def consultar_dados_pessoa_fisica_por_codigo(self, codigopessoa_fis: int | None = None) -> requests.Response: ...
    def consultar_dados_pessoa_por_cpf_cnpj_estatus(self, cpf_cnpj: str | None = None, status: int | None = None) -> requests.Response: ...
    def consultar_dados_adicionais_pessoa_por_chave(self, codigo_pessoa: int | None = None) -> requests.Response: ...
