from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Pessoas:
    def __init__(self, *args, **kwargs) -> None: ...
    def alterar_pessoa_acesso_portal(self, *args, **kwargs): ...
    def alterar_senha_cliente(self, *args, **kwargs): ...
    def consultar_contas_bancarias(self, *args, **kwargs): ...
    def consultar_dados_adicionais_pessoa_por_chave(self, *args, **kwargs): ...
    def consultar_dados_pessoa_fisica_por_codigo(self, *args, **kwargs): ...
    def consultar_dados_pessoa_por_cpf_cnpj_estatus(self, *args, **kwargs): ...
    def consultar_endereco_pessoas_por_chave(self, *args, **kwargs): ...
    def consultar_pessoa_por_chave(self, *args, **kwargs): ...
    def consultar_pessoas_com_venda(self, *args, **kwargs): ...
    def consultar_pessoas_funcionarios_ativos(self, *args, **kwargs): ...
    def consultar_pessoas_por_condicao(self, *args, **kwargs): ...
    def consultar_pessoas_por_cpfcnpj(self, *args, **kwargs): ...
    def consultar_telefone_pes_por_chave(self, *args, **kwargs): ...
    def consultar_telefones(self, *args, **kwargs): ...
    def consultar_tipo_endereco(self, *args, **kwargs): ...
    def consultar_unidades(self, *args, **kwargs): ...
    def criar_credenciais_uauweb(self, *args, **kwargs): ...
    def excluir_banco_econta_por_chave(self, *args, **kwargs): ...
    def excluir_telefone(self, *args, **kwargs): ...
    def gravar_conta_bancaria(self, *args, **kwargs): ...
    def gravar_pessoa(self, *args, **kwargs): ...
    def importar_dados_pessoas_para_uau(self, *args, **kwargs): ...
    def manter_telefone(self, *args, **kwargs): ...
    def recuperar_credenciais_uauweb(self, *args, **kwargs): ...
