from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Planejamento:
    def __init__(self, *args, **kwargs) -> None: ...
    def aprovar_solicitacao_planejamento(self, *args, **kwargs): ...
    def aprovar_solicitacao_planejamento_em_lote(self, *args, **kwargs): ...
    def aprovar_solicitacao_planejamento_insumos_em_lote(self, *args, **kwargs): ...
    def aprovar_solicitacao_planejamento_servicos_em_lote(self, *args, **kwargs): ...
    def atualizar_estrutura_planejamento(self, *args, **kwargs): ...
    def atualizar_insumos_planejamento(self, *args, **kwargs): ...
    def atualizar_item_planejamento(self, *args, **kwargs): ...
    def atualizar_servico_planejamento(self, *args, **kwargs): ...
    def atualizar_servico_planejamento_integrado(self, *args, **kwargs): ...
    def atualizar_servico_planejamento_mes(self, *args, **kwargs): ...
    def consultar_aprovacao_pl_pendente_por_usuario(self, *args, **kwargs): ...
    def consultar_desembolso_planejamento(self, *args, **kwargs): ...
    def consultar_estrutura_planejamento(self, *args, **kwargs): ...
    def consultar_item_planejamento(self, *args, **kwargs): ...
    def consultar_quantidade_aprovacao_pl_pendente_por_usuario(self, *args, **kwargs): ...
    def consultar_saldo_siplanejada(self, *args, **kwargs): ...
    def consultar_servico_planejado_desintegrado(self, *args, **kwargs): ...
    def consultar_servico_planejamento(self, *args, **kwargs): ...
    def consultar_servico_planejamento_integrado(self, *args, **kwargs): ...
    def consultar_servico_planejamento_mes(self, *args, **kwargs): ...
    def consultar_servico_planejamento_por_obra(self, *args, **kwargs): ...
    def consultar_solicitacao_insumo_pl(self, *args, **kwargs): ...
    def consultar_solicitacao_servico_pl(self, *args, **kwargs): ...
    def exportar_planejamento_produto(self, *args, **kwargs): ...
    def inserir_estrutura_planejamento(self, *args, **kwargs): ...
    def inserir_servico_planejamento(self, *args, **kwargs): ...
    def inserir_servico_planejamento_integrado(self, *args, **kwargs): ...
    def inserir_servico_planejamento_mes(self, *args, **kwargs): ...
    def recusar_solicitacao_planejamento_geral(self, *args, **kwargs): ...
    def recusar_solicitacao_planejamento_geral_em_lote(self, *args, **kwargs): ...
