import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Planejamento:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def atualizar_item_planejamento(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, descricao_item: str | None = None, usuario: str | None = None) -> requests.Response: ...
    def consultar_item_planejamento(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None) -> requests.Response: ...
    def consultar_saldo_siplanejada(self, empresa: int | None = None, obra: str | None = None, produto: int | None = None, contrato: int | None = None, item: str | None = None, servico: str | None = None, mes_pl: str | None = None, insumo: str | None = None) -> requests.Response: ...
    def inserir_servico_planejamento(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, tipo_de_custo: str | None = None, usuario: str | None = None) -> requests.Response: ...
    def exportar_planejamento_produto(self, empresa: int | None = None, obra: str | None = None, contrato: int | None = None, produto: int | None = None) -> requests.Response: ...
    def atualizar_insumos_planejamento(self, insumos: list[dict] | None = None, justificativa_aprovacao_pl: str | None = None) -> requests.Response: ...
    def atualizar_servico_planejamento(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, qtde: int | None = None, data_inicio: str | None = None, data_termino: str | None = None, usuario: str | None = None) -> requests.Response: ...
    def consultar_servico_planejamento(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None) -> requests.Response: ...
    def consultar_solicitacao_insumo_pl(self, num_solicitacao: int | None = None) -> requests.Response: ...
    def inserir_estrutura_planejamento(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, sequencia: str | None = None, codigo_item: str | None = None, tipo: int | None = None, qtde: int | None = None, usuario: str | None = None) -> requests.Response: ...
    def consultar_solicitacao_servico_pl(self, num_solicitacao: int | None = None) -> requests.Response: ...
    def inserir_servico_planejamento_mes(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, mes: str | None = None, qtde: int | None = None, usuario: str | None = None) -> requests.Response: ...
    def aprovar_solicitacao_planejamento(self, num_solicitacao: int | None = None, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None) -> requests.Response: ...
    def atualizar_estrutura_planejamento(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, sequencia: str | None = None, qtde: int | None = None, usuario: str | None = None) -> requests.Response: ...
    def consultar_estrutura_planejamento(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, sequencia: str | None = None) -> requests.Response: ...
    def atualizar_servico_planejamento_mes(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, mes: str | None = None, qtde: int | None = None, usuario: str | None = None) -> requests.Response: ...
    def consultar_desembolso_planejamento(self, empresa: int | None = None, obra: str | None = None, mes_inicial: str | None = None, mes_final: str | None = None) -> requests.Response: ...
    def consultar_servico_planejamento_mes(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, mes: str | None = None) -> requests.Response: ...
    def consultar_servico_planejamento_por_obra(self, empresa: int | None = None, obra: str | None = None) -> requests.Response: ...
    def inserir_servico_planejamento_integrado(self, empresa: int | None = None, obra: str | None = None, produto: str | None = None, contrato: str | None = None, item: str | None = None, servico: str | None = None, tipo_de_custo: str | None = None, codigo_externo: str | None = None, usuario: str | None = None) -> requests.Response: ...
    def recusar_solicitacao_planejamento_geral(self, num_solicitacao: int | None = None, num_solicitacoes: list[dict] | None = None, ids_itens_solicitacao: list[dict] | None = None, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None) -> requests.Response: ...
    def aprovar_solicitacao_planejamento_em_lote(self, num_solicitacoes: list[dict] | None = None, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None) -> requests.Response: ...
    def atualizar_servico_planejamento_integrado(self, codigo_externo: str | None = None, qtde: int | None = None, data_inicio: str | None = None, data_termino: str | None = None, usuario: str | None = None) -> requests.Response: ...
    def consultar_servico_planejado_desintegrado(self, empresa: int | None = None, obra: str | None = None) -> requests.Response: ...
    def consultar_servico_planejamento_integrado(self, codigo_externo: str | None = None) -> requests.Response: ...
    def consultar_aprovacao_pl_pendente_por_usuario(self, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None, empresas_obras: str | None = None, tipo_consulta_aprovacao: str | None = None, numero_dias: int | None = None) -> requests.Response: ...
    def recusar_solicitacao_planejamento_geral_em_lote(self, num_solicitacao: int | None = None, num_solicitacoes: list[dict] | None = None, ids_itens_solicitacao: list[dict] | None = None, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None) -> requests.Response: ...
    def aprovar_solicitacao_planejamento_insumos_em_lote(self, ids_itens_solicitacao: list[dict] | None = None, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None) -> requests.Response: ...
    def aprovar_solicitacao_planejamento_servicos_em_lote(self, num_solicitacao: int | None = None, chaves_servico: list[dict] | None = None, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None) -> requests.Response: ...
    def consultar_quantidade_aprovacao_pl_pendente_por_usuario(self, usuario: str | None = None, departamento: str | None = None, cargo: str | None = None, empresas_obras: str | None = None, tipo_consulta_aprovacao: str | None = None, numero_dias: int | None = None) -> requests.Response: ...
