from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class ProcessoPagamento:
    def __init__(self, *args, **kwargs) -> None: ...
    def aprovar_dvq(self, *args, **kwargs): ...
    def aprovar_processos(self, *args, **kwargs): ...
    def consultar_processos(self, *args, **kwargs): ...
    def gerar_nota_fiscal(self, *args, **kwargs): ...
    def gerar_nota_fiscal_produto_pelo_xml(self, *args, **kwargs): ...
    def gerar_nota_fiscal_servico_pelo_xml(self, *args, **kwargs): ...
    def gerar_nota_fiscal_transporte_pelo_xml(self, *args, **kwargs): ...
    def gerar_processo(self, *args, **kwargs): ...
    def gerar_processo_medicao(self, *args, **kwargs): ...
    def integrar_processo_pagamento_uauws(self, *args, **kwargs): ...
    def manutencao_parcelas_processo(self, *args, **kwargs): ...
    def manutencao_processo(self, *args, **kwargs): ...
    def retornar_parcelas_dvq(self, *args, **kwargs): ...
