from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Proposta:
    def __init__(self, *args, **kwargs) -> None: ...
    def atualizar_pedido_de_recebimento(self, *args, **kwargs): ...
    def cancelar_pedido_de_recebimento(self, *args, **kwargs): ...
    def cancelar_proposta(self, *args, **kwargs): ...
    def consultar_hierarquia_parcelas(self, *args, **kwargs): ...
    def consultar_pedido_de_recebimento(self, *args, **kwargs): ...
    def consultar_pedido_de_recebimento_uau(self, *args, **kwargs): ...
    def consultar_proposta_por_id(self, *args, **kwargs): ...
    def expirar_boletos(self, *args, **kwargs): ...
    def gerar_boleto(self, *args, **kwargs): ...
    def gravar_pedido_de_recebimento(self, *args, **kwargs): ...
    def gravar_proposta(self, *args, **kwargs): ...
    def processar_recebimento_parcelas(self, *args, **kwargs): ...
    def renegociar_proposta(self, *args, **kwargs): ...
    def retorna_valor_comissao_deducao_parcelas(self, *args, **kwargs): ...
    def retornar_valores_estrutura_comissao(self, *args, **kwargs): ...
    def traduzir_request_parcelas_geradas(self, *args, **kwargs): ...
    def traduzir_request_parcelas_selecionadas(self, *args, **kwargs): ...
    def vincular_arquivo_proposta(self, *args, **kwargs): ...
