import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Proposta:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def gerar_boleto(self, parcelas: list[dict] | None = None, datacalculo: datetime | None = None, antecipar: bool | None = None, reajustar: bool | None = None, excluirboletoexpirado: bool | None = None, formacobranca: int | None = None, boletosacadodetalhado: bool | None = None, carnetresvias: bool | None = None, validardadospendentes: bool | None = None, acrescentarresiduo: bool | None = None, usarpadraoboletoavulso: bool | None = None, agruparparcelas: bool | None = None, valor_boleto: int | None = None, padrao_cobranca: int | None = None, excluir_boletos_existentes: bool | None = None) -> requests.Response: ...
    def expirar_boletos(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def gravar_proposta(self, proposta: dict | None = None, proposta_pacelas_geradas: list[dict] | None = None, proposta_param_modelo_parcelas: list[dict] | None = None, proposta_param_parcelas: list[dict] | None = None, proposta_comissao: list[dict] | None = None, proposta_comissao_parc: list[dict] | None = None, proposta_itens: list[dict] | None = None, proposta_cliente: list[dict] | None = None, proposta_plano_index: list[dict] | None = None, proposta_seguro: list[dict] | None = None, proposta_custas_retencao: dict | None = None, proposta_custas_retencao_parcela: list[dict] | None = None, proposta_cap: list[dict] | None = None, proposta_shopping: dict | None = None) -> requests.Response: ...
    def cancelar_proposta(self, numero_proposta: int | None = None, cancelar_vendida: bool | None = None, excluir_boletos: bool | None = None) -> requests.Response: ...
    def renegociar_proposta(self, num_proposta: int | None = None, proposta_parcelas_geradas: list[dict] | None = None, parcelas_selecionadas: list[dict] | None = None, valor_desconto: int | None = None, valor_acrescimo: int | None = None, num_padrao_cobranca: int | None = None, termo_reserva: int | None = None) -> requests.Response: ...
    def consultar_proposta_por_id(self, num_proposta: int | None = None, valor_antecipado: int | None = None, data_calculo: datetime | None = None) -> requests.Response: ...
    def vincular_arquivo_proposta(self, arquivo: str | None = None, nome_arquivo: str | None = None, proposta: int | None = None, usuario: str | None = None) -> requests.Response: ...
    def gravar_pedido_de_recebimento(self, empresa: int | None = None, obra: str | None = None, num_contrato: int | None = None, estabelecimento: str | None = None, forma_pgto: int | None = None, qtde_parcelas: int | None = None, data_calculo: datetime | None = None, valor_liquido: int | None = None, tipo_recebimento: int | None = None, antecipacao: bool | None = None, parcelas: list[dict] | None = None) -> requests.Response: ...
    def cancelar_pedido_de_recebimento(self, empresa: int | None = None, obra: str | None = None, pedido: int | None = None) -> requests.Response: ...
    def consultar_hierarquia_parcelas(self, codigo: int | None = None) -> requests.Response: ...
    def atualizar_pedido_de_recebimento(self, empresa: int | None = None, obra: str | None = None, pedido: int | None = None) -> requests.Response: ...
    def consultar_pedido_de_recebimento(self, empresa: int | None = None, obra: str | None = None, pedido: int | None = None) -> requests.Response: ...
    def processar_recebimento_parcelas(self, recebimento: dict | None = None, forma_pagamento: dict | None = None) -> requests.Response: ...
    def consultar_pedido_de_recebimento_uau(self, numerontk: int | None = None, numero_pedido: int | None = None) -> requests.Response: ...
    def retornar_valores_estrutura_comissao(self, codigo_empresa: int | None = None, codigo_obra: str | None = None, codigo_vendedor: int | None = None, codigo_hierarquia: int | None = None, codigo_comissao: int | None = None, valor_total_comissao: int | None = None, valor_comissao_direta: int | None = None, produtos: list[dict] | None = None, parcelas: list[dict] | None = None) -> requests.Response: ...
    def retorna_valor_comissao_deducao_parcelas(self, codigo_hierarquia: int | None = None, codigo_modelo_venda: int | None = None, valor_total_produto: int | None = None, valor_total_comissao: int | None = None, valor_total_comissao_direta: int | None = None, parcelas_geradas: list[dict] | None = None, porcentagem_comissao: int | None = None, valor_item_proposta: int | None = None) -> requests.Response: ...
    def traduzir_request_parcelas_geradas(self, parameters: list[dict] | None = None) -> requests.Response: ...
    def traduzir_request_parcelas_selecionadas(self, parameters: list[dict] | None = None) -> requests.Response: ...
