import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Prospect:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def gravar_prospect(self, permitir_responsavel_sem_estrutura: bool | None = None, login: str | None = None, prospect: dict | None = None, prospect_fis: dict | None = None, prospect_interesse: dict | None = None, prospect_interesse_produtos: list[dict] | None = None, prospect_interesse_bairros: list[dict] | None = None, prospect_telefones: list[dict] | None = None, prospect_endereco_principal: dict | None = None, prospect_endereco_cobranca: dict | None = None, prospect_endereco_comercial: dict | None = None, prospect_dependente: list[dict] | None = None, responsavel: str | None = None, buscou_de_pessoas: bool | None = None, atualizar_pessoas: bool | None = None, mensagem_retorno: str | None = None, prospect_doc: list[dict] | None = None) -> requests.Response: ...
    def importar_prospect(self, xml: str | None = None) -> requests.Response: ...
    def listar_grau_parentesco(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def migrar_prospect_pessoa(self, numero_prospect: int | None = None) -> requests.Response: ...
    def consultar_todos_prospects(self, enum_opcao_todos: int | None = None, codigo_prospect: str | None = None, codigo_vendedor: int | None = None) -> requests.Response: ...
    def consultar_prospect_por_chave(self, codigo_prospect: int | None = None) -> requests.Response: ...
    def alterar_responsavel_prospect(self, novo_responsavel: int | None = None, cod_empresa: int | None = None, num_prospect: int | None = None) -> requests.Response: ...
    def consultar_prospect_com_filtro(self, numero_opcao: int | None = None, numero_visao: int | None = None, prospect_sem_responsavel: bool | None = None, codigo_responsavel: str | None = None, nome_pessoa: str | None = None, telefone: str | None = None, cpf_cnpj: str | None = None, trata_sem_responsavel: bool | None = None, uf_prosp: str | None = None) -> requests.Response: ...
    def buscar_grau_parentesco_por_codigo(self, codigo: int | None = None) -> requests.Response: ...
