from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Prospect:
    def __init__(self, *args, **kwargs) -> None: ...
    def alterar_responsavel_prospect(self, *args, **kwargs): ...
    def buscar_grau_parentesco_por_codigo(self, *args, **kwargs): ...
    def consultar_prospect_com_filtro(self, *args, **kwargs): ...
    def consultar_prospect_por_chave(self, *args, **kwargs): ...
    def consultar_todos_prospects(self, *args, **kwargs): ...
    def gravar_prospect(self, *args, **kwargs): ...
    def importar_prospect(self, *args, **kwargs): ...
    def listar_grau_parentesco(self, *args, **kwargs): ...
    def migrar_prospect_pessoa(self, *args, **kwargs): ...
