from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Recebiveis:
    def __init__(self, *args, **kwargs) -> None: ...
    def alterar_meio_preferencial_de_recebimento_da_parcela(self, *args, **kwargs): ...
    def by_numpadraocobranca(self, *args, **kwargs): ...
    def consultar_meios_preferenciais_recebimento(self, *args, **kwargs): ...
    def parcelas_ecobrancas_do_cliente(self, *args, **kwargs): ...
