import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Recebiveis:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def consultar_meios_preferenciais_recebimento(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def by_numpadraocobranca(self, id_empresa: str, num_padrao_cobranca: str, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def parcelas_ecobrancas_do_cliente(self, cpf: str | None = None, valor_reajustado: bool | None = None, qtde_parcelas: int | None = None, data_inicio_vencimento: datetime | None = None, data_fim_vencimento: datetime | None = None, pesquisa_por_nao_titulares: bool | None = None) -> requests.Response: ...
    def alterar_meio_preferencial_de_recebimento_da_parcela(self, empresa: int | None = None, obra: str | None = None, venda: int | None = None, numero_parcela: int | None = None, tipo_parcela: str | None = None, numero_parcela_geral: int | None = None, meio_preferencial_recebimento: int | None = None) -> requests.Response: ...
