from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class RelatorioIRPF:
    def __init__(self, *args, **kwargs) -> None: ...
    def gerar_pdfrel_irpf(self, *args, **kwargs): ...
    def gerar_pdfrel_irpfv2(self, *args, **kwargs): ...
