from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class RequisicaoCompra:
    def __init__(self, *args, **kwargs) -> None: ...
    def aprovar_requisicoes_compra(self, *args, **kwargs): ...
    def desaprovar_requisicoes_compra(self, *args, **kwargs): ...
