from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Reserva:
    def __init__(self, *args, **kwargs) -> None: ...
    def consulta_reserva_por_proposta(self, *args, **kwargs): ...
    def consultar_dados_controle_reserva(self, *args, **kwargs): ...
    def consultar_reserva_por_codigo(self, *args, **kwargs): ...
    def consultar_reserva_vendedor(self, *args, **kwargs): ...
    def consultar_reservas(self, *args, **kwargs): ...
    def excluir_reserva(self, *args, **kwargs): ...
    def gravar_reserva(self, *args, **kwargs): ...
