import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Reserva:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def gravar_reserva(self, dados_reserva_json: str | None = None) -> requests.Response: ...
    def excluir_reserva(self, empresa: int | None = None, obra: str | None = None, num_proposta: int | None = None, cod_produto: int | None = None, cod_person: int | None = None, cod_reserva: int | None = None) -> requests.Response: ...
    def consultar_reservas(self, empresa: int | None = None, cod_produto: int | None = None, cod_person: int | None = None, status: str | None = None) -> requests.Response: ...
    def consultar_reserva_vendedor(self, empresa: int | None = None, num_prod: int | None = None, num_per: int | None = None, vendedor: int | None = None) -> requests.Response: ...
    def consultar_reserva_por_codigo(self, empresa: int | None = None, cod_produto: int | None = None, cod_person: int | None = None, cod_reserva: int | None = None) -> requests.Response: ...
    def consulta_reserva_por_proposta(self, empresa: int | None = None, obra: str | None = None, num_proposta: int | None = None) -> requests.Response: ...
    def consultar_dados_controle_reserva(self, empresa: int | None = None, cod_produto: int | None = None, cod_person: int | None = None, status: str | None = None) -> requests.Response: ...
