from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class RotinasGerais:
    def __init__(self, *args, **kwargs) -> None: ...
    def busca_campos_person(self, *args, **kwargs): ...
    def busca_capvenda_empresa(self, *args, **kwargs): ...
    def buscar_categorias_de_produto(self, *args, **kwargs): ...
    def buscar_finalidades_de_compra(self, *args, **kwargs): ...
    def buscar_indices_de_reajuste(self, *args, **kwargs): ...
    def buscar_tipos_de_vencimento(self, *args, **kwargs): ...
    def buscar_veiculos_de_divulgacao(self, *args, **kwargs): ...
    def consultar_padroes_cobranca(self, *args, **kwargs): ...
    def consultar_param_consulta_geral(self, *args, **kwargs): ...
    def executar_consulta_geral(self, *args, **kwargs): ...
    def inserir_consulta_geral(self, *args, **kwargs): ...
