import requests
from _typeshed import Incomplete
from datetime import datetime as datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class RotinasGerais:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def busca_campos_person(self, empresa: str | None = None, produto: str | None = None) -> requests.Response: ...
    def busca_capvenda_empresa(self, codigo_empresa: int | None = None) -> requests.Response: ...
    def inserir_consulta_geral(self, clausula_sql: str | None = None, descricao: str | None = None, codigo_pasta: str | None = None, status: int | None = None, parametros: list[dict] | None = None) -> requests.Response: ...
    def executar_consulta_geral(self, id: int | None = None, personalizado: int | None = None, parameters: list[dict] | None = None) -> requests.Response: ...
    def buscar_indices_de_reajuste(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def buscar_tipos_de_vencimento(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def consultar_padroes_cobranca(self, empresa: int | None = None, status: int | None = None, banco: int | None = None) -> requests.Response: ...
    def buscar_categorias_de_produto(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def buscar_finalidades_de_compra(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def buscar_veiculos_de_divulgacao(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def consultar_param_consulta_geral(self, id: int | None = None, personalizado: int | None = None) -> requests.Response: ...
