from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Shopping:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_rendimento_lojista(self, *args, **kwargs): ...
    def grava_rendimentos(self, *args, **kwargs): ...
    def importacao_de_parcelas(self, *args, **kwargs): ...
