import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Shopping:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def grava_rendimentos(self, dia: datetime | None = None, lojista: bool | None = None, empresa: int | None = None, obra: str | None = None, venda: int | None = None, valor_lancamento: int | None = None, usuario: str | None = None, tipo_usuario: int | None = None) -> requests.Response: ...
    def importacao_de_parcelas(self, parcelas: list[dict] | None = None) -> requests.Response: ...
    def consultar_rendimento_lojista(self, cod_empresa: int | None = None, cod_obra: str | None = None, num_venda: int | None = None, ini_lancamento: datetime | None = None, fim_lancamento: datetime | None = None) -> requests.Response: ...
