from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Usuarios:
    def __init__(self, *args, **kwargs) -> None: ...
    def consultar_grupos_de_usuario(self, *args, **kwargs): ...
    def consultar_usuarios_ativos(self, *args, **kwargs): ...
