from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Venda:
    def __init__(self, *args, **kwargs) -> None: ...
    def alterar_data_prorrogacao(self, *args, **kwargs): ...
    def aprov_desaprov_reneg(self, *args, **kwargs): ...
    def atualizar_pedido_de_recebimento(self, *args, **kwargs): ...
    def busca_parc_reneg_web(self, *args, **kwargs): ...
    def buscar_campanha_desconto_venda(self, *args, **kwargs): ...
    def buscar_parametro_cobranca(self, *args, **kwargs): ...
    def buscar_parcelas_areceber(self, *args, **kwargs): ...
    def buscar_parcelas_recebidas(self, *args, **kwargs): ...
    def buscar_recebimentos_da_venda(self, *args, **kwargs): ...
    def buscar_status_cobranca(self, *args, **kwargs): ...
    def buscar_status_de_escritura(self, *args, **kwargs): ...
    def buscar_tipos_de_custas(self, *args, **kwargs): ...
    def buscar_tipos_de_parcelas(self, *args, **kwargs): ...
    def calcular_desconto_campanha_antecipacao(self, *args, **kwargs): ...
    def cancelar_pedido_de_recebimento(self, *args, **kwargs): ...
    def consultar_campanha_desconto_disponivel(self, *args, **kwargs): ...
    def consultar_contas_receber_calc(self, *args, **kwargs): ...
    def consultar_demonstrativo_correcao(self, *args, **kwargs): ...
    def consultar_desconto_antecipacao_parcela(self, *args, **kwargs): ...
    def consultar_empreendimentos_cliente(self, *args, **kwargs): ...
    def consultar_historicos(self, *args, **kwargs): ...
    def consultar_parcelas_da_venda(self, *args, **kwargs): ...
    def consultar_pedido_de_recebimento(self, *args, **kwargs): ...
    def consultar_pedido_de_recebimento_uau(self, *args, **kwargs): ...
    def consultar_plano_indexadores_venda(self, *args, **kwargs): ...
    def consultar_resumo_venda(self, *args, **kwargs): ...
    def consultar_unidades_compradas_por_cpf(self, *args, **kwargs): ...
    def consultar_unidades_compradas_por_cpfcnpj(self, *args, **kwargs): ...
    def consultar_unidades_compradas_usr_logado(self, *args, **kwargs): ...
    def excluir_parcela_custa(self, *args, **kwargs): ...
    def exclusao_de_boletos(self, *args, **kwargs): ...
    def exportar_pessoas_da_venda_xml(self, *args, **kwargs): ...
    def exportar_vendas_xml(self, *args, **kwargs): ...
    def finalizar_renegociacao(self, *args, **kwargs): ...
    def gerar_boleto_bancario(self, *args, **kwargs): ...
    def gerar_pdfevolucao_contrato(self, *args, **kwargs): ...
    def gerar_pdfevolucao_saldo_devedor_financiamento(self, *args, **kwargs): ...
    def gerar_pdfresumo_venda(self, *args, **kwargs): ...
    def gerar_venda_de_proposta(self, *args, **kwargs): ...
    def gravar_num_contrato_financiamento(self, *args, **kwargs): ...
    def gravar_ocorrencia_anexo(self, *args, **kwargs): ...
    def gravar_pedido_de_recebimento(self, *args, **kwargs): ...
    def importacao_de_venda(self, *args, **kwargs): ...
    def importacao_parcelas_de_custas(self, *args, **kwargs): ...
    def importacao_venda_com_retorno(self, *args, **kwargs): ...
    def manter_status_cobranca_venda(self, *args, **kwargs): ...
    def manter_status_escrituracao_venda(self, *args, **kwargs): ...
    def processar_recebimento_parcelas(self, *args, **kwargs): ...
    def renegociar_venda(self, *args, **kwargs): ...
    def retorna_chaves_vendas_por_periodo(self, *args, **kwargs): ...
    def venda_valida_para_manutencao(self, *args, **kwargs): ...
