from uau_api.requestsapi import RequestsApi as RequestsApi

__test__: dict

class Webhook:
    def __init__(self, *args, **kwargs) -> None: ...
    def atualizar_pedido_rec(self, *args, **kwargs): ...
    def atualizar_recebimento_pix(self, *args, **kwargs): ...
    def by_token(self, *args, **kwargs): ...
