import requests
from _typeshed import Incomplete
from datetime import datetime
from http import HTTPStatus as HTTPStatus
from uau_api.requestsapi import RequestsApi as RequestsApi

class Webhook:
    api: Incomplete
    def __init__(self, api: RequestsApi) -> None: ...
    def by_token(self, token: str, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
    def atualizar_recebimento_pix(self, end_to_end_id: str | None = None, txid: str | None = None, valor: str | None = None, horario: datetime | None = None, info_pagador: str | None = None, devolucoes: dict | None = None, pagador: dict | None = None) -> requests.Response: ...
    def atualizar_pedido_rec(self, detalhe: str | None = None, mensagem: str | None = None, descricao: str | None = None) -> requests.Response: ...
